// ═══════════════════════════════════════════════════════════════════════
// ESLint config — flat config (ESLint 9.x)
// ═══════════════════════════════════════════════════════════════════════
// Scope: every .js and .jsx under app/src/main/assets/src (the 159 source
// modules). Out of scope: dist (built output), .min.js (vendor),
// src/data (auto-generated corpus data, would be pure noise).
//
// NB: line comments throughout this header — block /* */ comments break
// when they contain JS-glob syntax like `src/**/*.js` because the `*/`
// inside the glob prematurely closes the block. Lesson learned.

// The projectGlobals object is AUTO-GENERATED by tools/gen-eslint-globals.py
// from the bundle entry files + index.html + corpus. Regenerate via:
//     npm run lint:globals
// `npm run lint` chains lint:globals first, and the pre-commit hook also
// regens — so the globals list cannot go stale relative to the bundles.
//
// Plugins:
//   - @eslint/js                — recommended base rules
//   - eslint-plugin-react       — JSX-aware (key warnings, jsx-uses-react,
//                                 jsx-no-undef, etc.). Applicable as of
//                                 Q2.7-2 — the entire UI surface is JSX.
//   - eslint-plugin-react-hooks — rules-of-hooks + exhaustive-deps.
//                                 Exhaustive-deps is the highest-value
//                                 bug-catcher here: would have caught the
//                                 journalEntryId stale-closure fixed in
//                                 P6l. NEVER auto-fixed (see Q3.3 plan).
//
// Rule philosophy:
//   - Base + react + react-hooks recommended sets.
//   - NO style rules (semi, indent, quotes). Style is Prettier's job —
//     a later phase, not this one.
//   - no-unused-vars warns, doesn't error (lots of _var placeholders
//     that the linter shouldn't reject outright).
// ═══════════════════════════════════════════════════════════════════════

import js from '@eslint/js';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import globals from 'globals';

import { projectGlobals } from './tools/eslint-globals.generated.js';

export default [
  // Global ignores — applies before any other config matches.
  {
    ignores: [
      'app/src/main/assets/dist/**',
      'app/src/main/assets/*.min.js',
      'app/src/main/assets/search-data.js',
      'app/src/main/assets/src/data/**',
      'app/src/main/assets/src/search/vendor/**',
      'node_modules/**',
      'tools/eslint-globals.generated.js',
    ],
  },

  // Base + React + React Hooks for all src/ files.
  {
    files: ['app/src/main/assets/src/**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
        ...projectGlobals,
        // Override: __scrollEl is module-mutable (declared `let` in inline #3
        // at index.html, written by ScreenLayout's ref callback). The
        // generator defaults all globals to readonly; this is the one
        // exception. If more module-mutable globals surface, list them here.
        __scrollEl: 'writable',
      },
    },
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    settings: {
      react: { version: '18.2' },
    },
    rules: {
      // Base recommended
      ...js.configs.recommended.rules,
      // React recommended
      ...reactPlugin.configs.recommended.rules,
      // React Hooks recommended (rules-of-hooks + exhaustive-deps)
      ...reactHooksPlugin.configs.recommended.rules,
      // Local tweaks
      // `new Function` is eval by another name. It is not in
      // eslint:recommended, so before this line any
      // `eslint-disable-next-line no-new-func` in this tree was DEAD — it
      // suppressed nothing and eslint reported it as an unused directive,
      // which `--max-warnings 0` (the CI invocation) rejects. Two branches
      // were handed over red on that in one night.
      //
      // The cause was a precedent, not carelessness: the only written-down
      // example of the idiom lives at tools/e2e-read-harness.test.js:270,
      // WITH a three-line justification and a directive — and `npm run lint`
      // covers only app/src/main/assets/src, so tools/ is never linted and
      // that directive is inert there. Copy it into a linted test and CI
      // rejects it. A precedent that is only correct because nobody checks it
      // is worse than no precedent, and the careful justification is exactly
      // what made the wrong form look authoritative.
      //
      // Turning the rule ON makes the surviving directives necessary and
      // honest instead of dead, and buys a real protection in place of a rule
      // nobody enforced.
      //
      // COST, RE-MEASURED ON THE TREE THIS LANDS ON (main e97112e6): THREE
      // `new Function` in the linted scope — `eslint app/src/main/assets/src`,
      // which is what `npm run lint` covers — at audio-track.editions.test.js:37
      // and :224, and audio-track.test.js:48, and zero `eval(`. So THREE
      // directives are added with this change and nothing else moves.
      //
      // THAT NUMBER HAS NOW GONE STALE THREE TIMES, which is the fact worth
      // carrying rather than the number:
      //
      //   d1b02128  1 site   "exactly one directive is added" — true of that base
      //   98de630f  2 sites  a gate-owns-its-data fix added one, and its dead
      //                      directive was dropped because this rule was off
      //   e97112e6  3 sites  c48's own manifest evaluation (06a39577)
      //
      // A COST IS A CLAIM ABOUT A BASE AND IT EXPIRES WHEN MAIN MOVES. Every
      // one of those landed changes is correct alone, and each was red against
      // this branch until the count was re-read on the landing tree. The census
      // is `web-builder-tools/nonewfunc-precut.sh <ref>`, and it is a PRE-CUT
      // check to run on every main move, not once: it derives the lint scope
      // from package.json, counts both forms the rule reports, and fails in
      // BOTH directions — a missing directive is an error and a surplus one is
      // an unused disable, which `--max-warnings 0` rejects just as hard.
      //
      // Anyone adding a `new Function` after this lands is told by CI, which is
      // the whole point of the rule being on rather than a comment asking.
      'no-new-func': 'error',
      // caughtErrorsIgnorePattern: '^_' makes `catch (_e)` exempt from
      // no-unused-vars's caughtErrors check (which defaults to 'all' in
      // ESLint 9). Matches the existing argsIgnorePattern / varsIgnorePattern
      // convention so all three unused-var classes share one prefix policy.
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'react/prop-types': 'off',   // JSDoc types will cover this (Q4 phase)
      'react/display-name': 'off', // anonymous components are fine in this codebase
      // jsx-no-undef's default is to ignore languageOptions.globals (legacy
      // eslintrc behavior). allowGlobals: true makes it respect the globals
      // list, which is the whole point of having a 322-entry generated list.
      'react/jsx-no-undef': ['error', { allowGlobals: true }],
      // no-empty: downgraded to warn (Q3.3b). Every empty catch in the
      // codebase intentionally swallows a non-fatal failure (localStorage
      // quota, IDB unsupported, native bridge missing, helper malformed-data).
      // Each site has a one-line inline reason comment naming the category.
      // The rule stays as warn so future empty-catch additions without a
      // reason still surface for review. See Q3 exit criteria — no-empty
      // warnings are an accepted category alongside exhaustive-deps and
      // no-unused-vars.
      'no-empty': 'warn',

      /* webkit-compat-1. `requestIdleCallback` has never shipped in WebKit —
         no Safari, and no iOS browser of any brand, since every iOS engine is
         WebKit. A bare reference is a ReferenceError on those devices, not a
         graceful degradation. Every call site here did carry the guard, and
         the most recent one carried it by hand again, which is the shape that
         eventually forgets. utils/on-idle.js is the guard, once; this rule is
         what stops the bare global coming back past review. */
      'no-restricted-globals': ['error',
        { name: 'requestIdleCallback', message: 'WebKit has never shipped it. Use onIdle() from utils/on-idle.js — it carries the guard, the timeout and the matching cancel.' },
        { name: 'cancelIdleCallback', message: 'Use the cancel function onIdle() returns; it knows which API it scheduled with.' },
      ],

      // ─── React Compiler rule shed (Q3.3a-compiler-disable) ────────────────
      // eslint-plugin-react-hooks@7's recommended set ships 16 rules. Two of
      // them (rules-of-hooks, exhaustive-deps) are the canonical pair every
      // React app needs. The other 14 are React Compiler analysis rules —
      // they enforce invariants the optimizing compiler relies on. This
      // codebase is React 18.2 with no Compiler in use or planned, so those
      // 14 rules are forward-looking constraints that don't catch any
      // runtime bug today. Disabling them wholesale eliminates 54 baseline
      // errors with zero behavioral impact.
      //
      // set-state-in-render: real-bug class (infinite render loop) and worth
      // keeping defensively — BUT current baseline shows 0 hits, so disabling
      // it now matches the "shed everything Compiler-era while clean" policy.
      // If a real call-setter-in-render bug appears later, exhaustive-deps +
      // a careful review during Q4 (types) will catch the worst variants.
      // ──────────────────────────────────────────────────────────────────────
      'react-hooks/static-components': 'off',
      'react-hooks/use-memo': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/incompatible-library': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/globals': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/error-boundaries': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-render': 'off',
      'react-hooks/unsupported-syntax': 'off',
      'react-hooks/config': 'off',
      'react-hooks/gating': 'off',
    },
  },
];
