// ═══════════════════════════════════════════════════════════════════════
// ESLint config — flat config (ESLint 9.x)
// ═══════════════════════════════════════════════════════════════════════
// Scope: every .js and .jsx under app/src/main/assets/src (the 159 source
// modules). Out of scope: dist (built output), .min.js (vendor),
// src/data (auto-generated corpus data, would be pure noise).
//
// NB: line comments throughout this header — block /* */ comments break
// when they contain JS-glob syntax like `src/**/*.js` because the `*/`
// inside the glob prematurely closes the block. Lesson learned.

// The projectGlobals object is AUTO-GENERATED by tools/gen-eslint-globals.py
// from the bundle entry files + index.html + corpus. Regenerate via:
//     npm run lint:globals
// `npm run lint` chains lint:globals first, and the pre-commit hook also
// regens — so the globals list cannot go stale relative to the bundles.
//
// Plugins:
//   - @eslint/js                — recommended base rules
//   - eslint-plugin-react       — JSX-aware (key warnings, jsx-uses-react,
//                                 jsx-no-undef, etc.). Applicable as of
//                                 Q2.7-2 — the entire UI surface is JSX.
//   - eslint-plugin-react-hooks — rules-of-hooks + exhaustive-deps.
//                                 Exhaustive-deps is the highest-value
//                                 bug-catcher here: would have caught the
//                                 journalEntryId stale-closure fixed in
//                                 P6l. NEVER auto-fixed (see Q3.3 plan).
//
// Rule philosophy:
//   - Base + react + react-hooks recommended sets.
//   - NO style rules (semi, indent, quotes). Style is Prettier's job —
//     a later phase, not this one.
//   - no-unused-vars warns, doesn't error (lots of _var placeholders
//     that the linter shouldn't reject outright).
// ═══════════════════════════════════════════════════════════════════════

import js from '@eslint/js';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import globals from 'globals';

import { projectGlobals } from './tools/eslint-globals.generated.js';

export default [
  // Global ignores — applies before any other config matches.
  {
    ignores: [
      'app/src/main/assets/dist/**',
      'app/src/main/assets/*.min.js',
      'app/src/main/assets/search.js',
      'app/src/main/assets/search-data.js',
      'app/src/main/assets/src/data/**',
      'app/src/main/assets/src/search/vendor/**',
      'node_modules/**',
      'tools/eslint-globals.generated.js',
    ],
  },

  // Base + React + React Hooks for all src/ files.
  {
    files: ['app/src/main/assets/src/**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
        ...projectGlobals,
        // Override: __scrollEl is module-mutable (declared `let` in inline #3
        // at index.html, written by ScreenLayout's ref callback). The
        // generator defaults all globals to readonly; this is the one
        // exception. If more module-mutable globals surface, list them here.
        __scrollEl: 'writable',
      },
    },
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    settings: {
      react: { version: '18.2' },
    },
    rules: {
      // Base recommended
      ...js.configs.recommended.rules,
      // React recommended
      ...reactPlugin.configs.recommended.rules,
      // React Hooks recommended (rules-of-hooks + exhaustive-deps)
      ...reactHooksPlugin.configs.recommended.rules,
      // Local tweaks
      // caughtErrorsIgnorePattern: '^_' makes `catch (_e)` exempt from
      // no-unused-vars's caughtErrors check (which defaults to 'all' in
      // ESLint 9). Matches the existing argsIgnorePattern / varsIgnorePattern
      // convention so all three unused-var classes share one prefix policy.
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'react/prop-types': 'off',   // JSDoc types will cover this (Q4 phase)
      'react/display-name': 'off', // anonymous components are fine in this codebase
      // jsx-no-undef's default is to ignore languageOptions.globals (legacy
      // eslintrc behavior). allowGlobals: true makes it respect the globals
      // list, which is the whole point of having a 322-entry generated list.
      'react/jsx-no-undef': ['error', { allowGlobals: true }],
      // no-empty: downgraded to warn (Q3.3b). Every empty catch in the
      // codebase intentionally swallows a non-fatal failure (localStorage
      // quota, IDB unsupported, native bridge missing, helper malformed-data).
      // Each site has a one-line inline reason comment naming the category.
      // The rule stays as warn so future empty-catch additions without a
      // reason still surface for review. See Q3 exit criteria — no-empty
      // warnings are an accepted category alongside exhaustive-deps and
      // no-unused-vars.
      'no-empty': 'warn',

      // ─── React Compiler rule shed (Q3.3a-compiler-disable) ────────────────
      // eslint-plugin-react-hooks@7's recommended set ships 16 rules. Two of
      // them (rules-of-hooks, exhaustive-deps) are the canonical pair every
      // React app needs. The other 14 are React Compiler analysis rules —
      // they enforce invariants the optimizing compiler relies on. This
      // codebase is React 18.2 with no Compiler in use or planned, so those
      // 14 rules are forward-looking constraints that don't catch any
      // runtime bug today. Disabling them wholesale eliminates 54 baseline
      // errors with zero behavioral impact.
      //
      // set-state-in-render: real-bug class (infinite render loop) and worth
      // keeping defensively — BUT current baseline shows 0 hits, so disabling
      // it now matches the "shed everything Compiler-era while clean" policy.
      // If a real call-setter-in-render bug appears later, exhaustive-deps +
      // a careful review during Q4 (types) will catch the worst variants.
      // ──────────────────────────────────────────────────────────────────────
      'react-hooks/static-components': 'off',
      'react-hooks/use-memo': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/incompatible-library': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/globals': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/error-boundaries': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-render': 'off',
      'react-hooks/unsupported-syntax': 'off',
      'react-hooks/config': 'off',
      'react-hooks/gating': 'off',
    },
  },
];
