"""Atlas areas in the inventory's order. Each area lists name patterns (fnmatch); first matching area wins.
Within an area, screens sort by the index of the first pattern they match, then by name."""

AREAS = [
    ('home', 'Home & navigation', 'Launch, Home, the top bar and the Surprise Me button.',
     ['dl-splash', 'home', 'home-tabs', 'dl-home-reorder', 'sy-topbar*', 'sy-surprise*']),
    ('letters', 'Reading: the letters', 'The Volumes, their letter indexes and the letter page in every variant.',
     ['volumes', 'index', 'bs-collections', 'letter', 'letter-focus', 'rd-letter*', 'rd-prophecy*', 'rd-related*', 'rd-arrows*', 'rd-flows*',
      'sy-sticky*', 'sy-bottom*', 'sy-autoscroll*', 'au-readalong*']),
    ('collections', 'Words To Live By, The Blessed & Holy Days', 'The Format B collections: inline citations that open the verse.',
     ['fb-wtlb*', 'fb-blessed*', 'fb-holy*']),
    ('bible', 'Reading: the Bible', 'Scripture browsing, the chapter reader, translations and the Restored Name editions.',
     ['scriptures', 'mt-layouts*', 'bs-genre*', 'bs-book*', 'bs-chapter*', 'mt-chapter*', 'mt-psalms*', 'mt-restored*', 'bs-translation*', 'bible-select']),
    ('footnotes', 'Footnotes & cross-references', 'Numbered bubbles, the verse sheet, the end-of-letter list and the wide-screen rail.',
     ['sheet', 'sheet-stack', 'rd-footnote*', 'rd-rail*']),
    ('annotation', 'Highlights, notes & marks', 'The selection toolbar, the ten colours, notes and their sub-sheets.',
     ['an-toolbar*', 'an-marks*', 'an-chip*', 'lb-note*', 'an-note*', 'an-notebook*', 'lb-bookmark-popover*', 'lb-copy*', 'an-confirm*', 'an-*']),
    ('search', 'Search', 'Search in every state, from the first keystroke to the rarest error.',
     ['sy-search-idle*', 'sy-search-typing*', 'sx-slash*', 'sx-direct*', 'search', 'sy-search-filters*', 'sx-groups*', 'sx-kinds*', 'sx-scope*',
      'sx-recent*', 'sx-from*', 'sy-search-noresults*', 'sy-search-loading*', 'sx-states*', 'sx-in-list*', 'sy-search*', 'sx-*']),
    ('links', 'Links', 'Linking any passage to any other, down to the deepest picker state.',
     ['lb-links*', 'lk-links*', 'lb-link-picker*', 'lk-modes*', 'lk-picker*', 'lk-verse*', 'lk-excerpt*', 'lk-created*', 'lb-link-card*', 'lb-link-sidebar*', 'lk-*', 'lb-link*']),
    ('library', 'Library: notes, bookmarks & marks', 'The Personal Study hub and its collections.',
     ['lb-library*', 'lb-notes*', 'lb-bookmarks*', 'highlights']),
    ('journal', 'Journal', 'The private journal: entries, blocks, media and voice memos.',
     ['jp-journal-hub*', 'jp-journal-viewer*', 'journal', 'jn-blocks*', 'jn-insert*', 'jn-pickers*', 'jn-reorder*', 'jn-recording*', 'jp-journal*',
      'jn-delete*', 'jn-banners*', 'lb-journal*', 'jn-*']),
    ('progress', 'Progress, milestones & history', 'A calm record of reading, with no streak pressure.',
     ['history', 'jp-progress*', 'jp-milestones*', 'jp-reading*']),
    ('tabs', 'Tabs', 'Reading places side by side.',
     ['tabs', 'dl-tab*', 'dl-disable*']),
    ('audio', 'Listening', 'The Listening Library, the listening desk, downloads and read-along.',
     ['au-library*', 'au-volumes*', 'au-collection*', 'au-studies*', 'au-saved*', 'au-offline*', 'au-lists*', 'player', 'ad-queue*', 'ad-voice*',
      'ad-speed*', 'player-sleep', 'ad-coverage*', 'ad-downloads*', 'au-mini*', 'media']),
    ('songs', 'Songs of the Letters', 'Songs made by the flock from the words of the letters.',
     ['au-songs*', 'ad-song-browse*', 'au-song*', 'ad-song*']),
    ('studies', 'Studies & the Matthew Study Bible', 'Bible/Letter Studies, the Matthew Study Bible and its study-notes modes.',
     ['studies', 'mt-studies*', 'bs-study*', 'bs-matthew-index*', 'bs-matthew*', 'mt-matthew*', 'mt-scripture*', 'bs-hidden*']),
    ('answers', 'Answers Only God Can Give', 'Topics and doctrines, the Ten Commandments and the ask box.',
     ['answers', 'sx-answers*', 'fb-commandment*', 'fb-answers-az*', 'fb-answers-subject*', 'fb-answers-entry*', 'fb-answers*']),
    ('web', 'Scripture Web', '63,418 cross-references drawn as threads, plus My Web, the reader\'s own links.',
     ['sw-loading*', 'web', 'sw-chrome*', 'sw-guide*', 'web-thread', 'sw-tips*', 'sw-chooser*', 'sw-nearby*', 'sw-detail*', 'sw-sky*',
      'sw-myweb*', 'sw-fail*', 'sw-*']),
    ('garden', 'A Return to The Garden', '209 photographs, streamed and cached.',
     ['dl-garden-gate*', 'jp-garden*', 'dl-garden*']),
    ('settings', 'Settings', 'Every group opened, every control shown.',
     ['settings', 'st-find*', 'appearance', 'st-reading*', 'st-listening*', 'st-autoscroll*', 'st-navbar*', 'st-search*', 'st-mark*', 'st-garden*',
      'st-help*', 'st-about*', 'st-pickers*', 'st-*']),
    ('data', 'Your data & storage health', 'Backup, verify, import and the banners that protect the reader\'s data.',
     ['yourdata', 'yd-version*', 'yd-verify*', 'yd-import*', 'yd-wipe*', 'yd-toasts*', 'yd-storage*', 'yd-updates*', 'yd-diagnostic*', 'yd-*']),
    ('onboarding', 'Welcome, About, tour & hints', 'First run, the eleven-stop tour and every quiet hint.',
     ['onboarding', 'jp-about*', 'sy-tour*', 'sy-hints*', 'dl-ios*']),
    ('system', 'System states & errors', 'Offline, missing content and crash states, written calm and helpful.',
     ['sy-errors*', 'yd-crash*', 'bs-states*', 'fb-states*', 'jp-*states*', 'sy-*']),
    ('brand', 'Components, icons, app icon & widget', 'The kit itself, and the app outside the app.',
     ['components', 'icons', 'appicon']),
    ('concepts', 'Concepts', 'Ideas beyond what the app does today, drawn for discussion and labelled as concepts.',
     ['web-prophecy', 'widget']),
]
# anything unmatched lands in a visible 'Unsorted' area so nothing is silently dropped
