"""Build script — concatenate Cluster A into a single classic-script bundle.

After G.2.1/G.2.2/G.2.3, Clusters B, C, and D are bundled by esbuild as
ES-module → IIFE bundles. This script now only emits bundle-a.js (vendor
+ raw corpus + search engine), which remains classic-script forever (no
benefit to converting third-party libs + ~1.5 MB of static data files to
ES modules).

CLUSTER OWNERSHIP:
  A — vendor + raw corpus + search engine                  (Python concat — this script)
  B — stores + components + hooks + journal + scripture    (esbuild → bundle-b.js)
  C — renderer (annotation engine + DOM bridges)           (esbuild → bundle-c.js)
  D — screens + sheets + components + utils + late stores  (esbuild → bundle-d.js)

The clusters are determined by the position of inline `<script>` blocks
in index.html. Inline blocks separate clusters because they declare
symbols used by following clusters AND reference symbols from prior
clusters; the load order between inlines and externals can't be
shuffled.

Run:
  python tools/build.py            # emits bundle-a.js only
  npm run build                    # full chain: this script + esbuild B/C/D

Output:
  app/src/main/assets/dist/bundle-a.js
"""
import os, sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

# Repo paths resolved relative to THIS script (tools/build.py) so the
# build runs identically on any machine and on CI — no hardcoded path.
_HERE = os.path.dirname(os.path.abspath(__file__))
REPO  = os.path.dirname(_HERE)
ROOT  = os.path.join(REPO, 'app', 'src', 'main', 'assets')
DIST  = os.path.join(ROOT, 'dist')

# Cluster A — vendor + (most) corpus + search engine (CRITICAL PATH).
# Bible (books.js, 6.9 MB) is lazy-loaded via bundle-a-bible.js.
# Matthew Study Bible (matthew.js, 618 KB) is lazy-loaded via
# bundle-a-matthew.js.
# See BUNDLE-LAZY-LOAD-PLAN.md (Q8.0) for the design rationale.
A = [
    'react.min.js', 'react-dom.min.js', 'html2canvas.min.js',
    'src/data/books-restored.js',
    'src/data/matthew-plain.js', 'src/data/matthew-nkjv.js',
    'src/data/volume-one.js', 'src/data/volume-two.js', 'src/data/volume-three.js',
    'src/data/volume-four.js', 'src/data/volume-five.js', 'src/data/volume-six.js',
    'src/data/volume-seven.js',
    'src/data/letters-timothy.js', 'src/data/letters-flock.js', 'src/data/lords-rebuke.js',
    'src/data/wtlb-one.js', 'src/data/wtlb-two.js', 'src/data/wtlb-scriptures.js',
    'src/data/the-blessed.js', 'src/data/holy-days.js', 'src/data/hidden-manna.js',
    'flexsearch.min.js', 'search-data.js', 'search.js',
]

# Cluster A-bible — the 66-book NKJV corpus. Loaded ON DEMAND via
# window.__loadBibleCorpus() (see index.html ~line 67). Until this
# bundle loads, `BOOKS` is undefined; consumers (ScripturesHome,
# Bible-bound nav handlers, BibleChapterView, useReadingChainNav,
# useSurprise's Bible branch) either show skeleton state or await
# __loadBibleCorpus() before rendering / navigating.
A_BIBLE = [
    'src/data/books.js',
]

# Cluster A-matthew — the Matthew Study Bible. Loaded ON DEMAND via
# window.__loadMatthewCorpus() on first navigation to Matthew Study
# Bible content (Studies → Matthew Study Bible, or any chain
# navigation that crosses into Matthew). Until this bundle loads,
# `MATTHEW` is undefined; ALL_BOOKS, useBibleStudies' Matthew chain,
# useSurprise's matthew branch, MatthewChapterView all guard.
A_MATTHEW = [
    'src/data/matthew.js',
]

# Cluster B — stores + components + hooks + journal subsystem + scripture-resolution
# (NOW BUNDLED VIA ESBUILD as of G.2.2).
# This list is kept empty; the source files use ES `export` syntax now.
# See package.json `build:b` for the esbuild invocation.
B = []  # intentionally empty; esbuild owns bundle-b.js

# Cluster C — renderer (NOW BUNDLED VIA ESBUILD as of G.2.1).
# This list is kept for reference; tools/build.py no longer emits bundle-c.js.
# See tools/build-esbuild.sh (or package.json `build:c`) for the esbuild
# invocation. The classic-script concat is dead for this cluster — the
# source files use ES `export` syntax now.
C = []  # intentionally empty; esbuild owns bundle-c.js

# Cluster D — screens + sheets + components + utils + late stores
# (NOW BUNDLED VIA ESBUILD as of G.2.3).
# This list is kept empty; the source files use ES `export` syntax now.
# See package.json `build:d` for the esbuild invocation (entry point:
# src/ui/_entry-d.js).
D = []  # intentionally empty; esbuild owns bundle-d.js


def bundle(name, files):
    out_path = os.path.join(DIST, 'bundle-' + name + '.js')
    parts = []
    parts.append('/* ' + '=' * 67 + '\n')
    parts.append('   G.1 BUNDLE ' + name.upper() + ' — ' + str(len(files)) + ' files concatenated\n')
    parts.append('   Generated by tools/build.py. DO NOT EDIT BY HAND — edit src/* files.\n')
    parts.append('   ' + '=' * 67 + ' */\n\n')
    total = 0
    for rel in files:
        path = os.path.join(ROOT, rel.replace('/', os.sep))
        if not os.path.isfile(path):
            print('FATAL: file not found:', rel)
            sys.exit(1)
        with open(path, 'r', encoding='utf-8', newline='') as f:
            content = f.read()
        parts.append('\n/* ' + '-' * 60 + '\n')
        parts.append(' * ' + rel + '\n')
        parts.append(' * ' + '-' * 60 + ' */\n')
        parts.append(content)
        if not content.endswith('\n'):
            parts.append('\n')
        total += len(content)
    os.makedirs(DIST, exist_ok=True)
    with open(out_path, 'w', encoding='utf-8', newline='') as f:
        out = ''.join(parts)
        f.write(out)
    print('OK: ' + name + ' = ' + str(len(files)) + ' files, ' + str(total) + ' raw bytes, ' + str(len(out)) + ' bundle bytes')


def main():
    print('Building 3 classic-script bundles --> ' + DIST)
    print('  (clusters B, C, D are bundled by esbuild; run `npm run build` for the full chain)')
    bundle('a', A)
    bundle('a-bible', A_BIBLE)
    bundle('a-matthew', A_MATTHEW)
    print('Done. (bundle-b.js, bundle-c.js, bundle-d.js belong to esbuild now.)')


if __name__ == '__main__':
    main()
