// AUTO-GENERATED by tools/gen-eslint-globals.py — do not hand-edit.
// Regenerate via `npm run lint:globals`.
//
// The hook globals as `any`, for tsconfig.strict-data.json: typed, they would
// pull every hook module into its strictNullChecks program.

declare const useAndroidBack: any;
declare const useAudioFollow: any;
declare const useAutoScroll: any;
declare const useBibleStudies: any;
declare const useDesktopKeyboard: any;
declare const useDocumentTitle: any;
declare const useDomAnnotationSync: any;
declare const useFocusTrap: any;
declare const useFromLetterStack: any;
declare const useFullscreenGesture: any;
declare const useHistory: any;
declare const useHistorySync: any;
declare const useJournalMediaSweep: any;
declare const useJournalMutations: any;
declare const useKeyboardInset: any;
declare const useLazyBundles: any;
declare const useMarkAsRead: any;
declare const useModalRegistry: any;
declare const useNav: any;
declare const useNavHistoryTracking: any;
declare const useNavigateToLink: any;
declare const usePersistedState: any;
declare const useRailMode: any;
declare const useReadProgress: any;
declare const useReadTracker: any;
declare const useReadingChainNav: any;
declare const useReadingDwell: any;
declare const useReadingPositionNav: any;
declare const useRefMirror: any;
declare const useRestoreGuard: any;
declare const useSavedState: any;
declare const useScrollMemory: any;
declare const useSearch: any;
declare const useSettings: any;
declare const useSharedPassageLink: any;
declare const useSheetOrchestration: any;
declare const useStorageInfo: any;
declare const useSurprise: any;
declare const useTabActions: any;
declare const useTabTitleMemo: any;
declare const useTabs: any;
declare const useTapThrough: any;
declare const useThumbnails: any;
declare const useTour: any;
declare const useTranslationLoader: any;
