// AUTO-GENERATED by tools/gen-eslint-globals.py — do not hand-edit.
// Regenerate via `npm run lint:globals`.
//
// The hook globals, typed from the src/hooks module that exports each
// (v15-code-health-09). tsconfig.json reads this file; tsconfig.strict-data.json
// reads hook-globals.any.generated.d.ts instead.

declare const useAndroidBack: typeof import('../app/src/main/assets/src/hooks/use-android-back.js').useAndroidBack;
declare const useAudioFollow: typeof import('../app/src/main/assets/src/hooks/use-audio-follow.js').useAudioFollow;
declare const useAutoScroll: typeof import('../app/src/main/assets/src/hooks/use-autoscroll.js').useAutoScroll;
declare const useBibleStudies: typeof import('../app/src/main/assets/src/hooks/use-bible-studies.js').useBibleStudies;
declare const useDesktopKeyboard: typeof import('../app/src/main/assets/src/hooks/use-desktop-keyboard.js').useDesktopKeyboard;
declare const useDocumentTitle: typeof import('../app/src/main/assets/src/hooks/use-document-title.js').useDocumentTitle;
declare const useDomAnnotationSync: typeof import('../app/src/main/assets/src/hooks/use-dom-annotation-sync.js').useDomAnnotationSync;
declare const useFocusTrap: typeof import('../app/src/main/assets/src/hooks/use-focus-trap.js').useFocusTrap;
declare const useFromLetterStack: typeof import('../app/src/main/assets/src/hooks/use-from-letter-stack.js').useFromLetterStack;
declare const useFullscreenGesture: typeof import('../app/src/main/assets/src/hooks/use-fullscreen-gesture.js').useFullscreenGesture;
declare const useHistory: typeof import('../app/src/main/assets/src/hooks/use-history.js').useHistory;
declare const useHistorySync: typeof import('../app/src/main/assets/src/hooks/use-history-sync.js').useHistorySync;
declare const useJournalMediaSweep: typeof import('../app/src/main/assets/src/hooks/use-journal-media-sweep.js').useJournalMediaSweep;
declare const useJournalMutations: typeof import('../app/src/main/assets/src/hooks/use-journal-mutations.js').useJournalMutations;
declare const useKeyboardInset: typeof import('../app/src/main/assets/src/hooks/use-keyboard-inset.js').useKeyboardInset;
declare const useLazyBundles: typeof import('../app/src/main/assets/src/hooks/use-lazy-bundles.js').useLazyBundles;
declare const useMarkAsRead: typeof import('../app/src/main/assets/src/hooks/useMarkAsRead.js').useMarkAsRead;
declare const useModalRegistry: typeof import('../app/src/main/assets/src/hooks/use-modal-registry.js').useModalRegistry;
declare const useNav: typeof import('../app/src/main/assets/src/hooks/use-nav.js').useNav;
declare const useNavHistoryTracking: typeof import('../app/src/main/assets/src/hooks/use-nav-history-tracking.js').useNavHistoryTracking;
declare const useNavigateToLink: typeof import('../app/src/main/assets/src/hooks/use-navigate-to-link.js').useNavigateToLink;
declare const usePersistedState: typeof import('../app/src/main/assets/src/hooks/use-persisted-state.js').usePersistedState;
declare const useRailMode: typeof import('../app/src/main/assets/src/hooks/use-rail-mode.js').useRailMode;
declare const useReadProgress: typeof import('../app/src/main/assets/src/hooks/useMarkAsRead.js').useReadProgress;
declare const useReadTracker: typeof import('../app/src/main/assets/src/hooks/use-read-tracker.js').useReadTracker;
declare const useReadingChainNav: typeof import('../app/src/main/assets/src/hooks/use-reading-chain-nav.js').useReadingChainNav;
declare const useReadingDwell: typeof import('../app/src/main/assets/src/hooks/use-reading-dwell.js').useReadingDwell;
declare const useReadingPositionNav: typeof import('../app/src/main/assets/src/hooks/use-reading-position-nav.js').useReadingPositionNav;
declare const useRefMirror: typeof import('../app/src/main/assets/src/hooks/use-ref-mirror.js').useRefMirror;
declare const useRestoreGuard: typeof import('../app/src/main/assets/src/hooks/use-restore-guard.js').useRestoreGuard;
declare const useSavedState: typeof import('../app/src/main/assets/src/hooks/use-saved-state.js').useSavedState;
declare const useScrollMemory: typeof import('../app/src/main/assets/src/hooks/use-scroll-memory.js').useScrollMemory;
declare const useSearch: typeof import('../app/src/main/assets/src/hooks/use-search.js').useSearch;
declare const useSettings: typeof import('../app/src/main/assets/src/hooks/use-settings.js').useSettings;
declare const useSharedPassageLink: typeof import('../app/src/main/assets/src/hooks/use-shared-passage-link.js').useSharedPassageLink;
declare const useSheetOrchestration: typeof import('../app/src/main/assets/src/hooks/use-sheet-orchestration.js').useSheetOrchestration;
declare const useStorageInfo: typeof import('../app/src/main/assets/src/hooks/use-storage-info.js').useStorageInfo;
declare const useSurprise: typeof import('../app/src/main/assets/src/hooks/use-surprise.js').useSurprise;
declare const useTabActions: typeof import('../app/src/main/assets/src/hooks/use-tab-actions.js').useTabActions;
declare const useTabTitleMemo: typeof import('../app/src/main/assets/src/hooks/use-tab-title-memo.js').useTabTitleMemo;
declare const useTabs: typeof import('../app/src/main/assets/src/hooks/use-tabs.js').useTabs;
declare const useTapThrough: typeof import('../app/src/main/assets/src/hooks/use-tap-through.js').useTapThrough;
declare const useThumbnails: typeof import('../app/src/main/assets/src/hooks/use-thumbnails.js').useThumbnails;
declare const useTour: typeof import('../app/src/main/assets/src/hooks/use-tour.js').useTour;
declare const useTranslationLoader: typeof import('../app/src/main/assets/src/hooks/use-translation-loader.js').useTranslationLoader;
