"""Mirror the audio-letter tracks to GitHub Releases (the app's stream host).

WHY THIS EXISTS (2026-08-06): Google Drive 403s every request whose
Sec-Fetch-Site is `cross-site` — hard anti-hotlinking on
drive.usercontent.google.com, so a web/WebView <audio> can NEVER stream
Drive directly (verified: same 403 from headless Chrome, real Chrome, and
the on-device WebView; a curl WITHOUT sec-fetch headers sails through,
which is what made the endpoint look viable). GitHub release assets have
no such gate, support Range, and already host the Garden images
(votreader-assets) — so the tracks mirror there and audio-player.js's
trackUrl() points at the release.

Usage:
  python tools/fetch-drive-audio.py               # refresh Drive listing
  node tools/gen-audio-manifest.mjs               # refresh manifest
  python tools/mirror-audio-release.py [--limit N] [--dry]

Idempotent + additive: skips assets already on the release, so a re-run
after the flock uploads new tracks only transfers the new files. Assets
are named <driveFileId>.mp3 — the manifest's ids double as asset names,
so a manifest regen needs NO url rewrites here.

Needs: gdown (pip) + gh CLI authed as VOTReader.
"""
import json, os, re, subprocess, sys, time

import gdown

REPO = "VOTReader/votreader-assets"
TAG = "audio-v1"
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MANIFEST = os.path.join(ROOT, "app", "src", "main", "assets", "src", "data", "audio-manifest.js")
STAGING = os.path.join(HERE, "_audio-mirror-staging")
GH = r"C:\Program Files\GitHub CLI\gh.exe"

sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def manifest_ids():
    """Every drive file id the app can play: letter parts + section comps."""
    text = open(MANIFEST, encoding="utf-8").read()
    # Tuples look like ["<id>","B"] / ["<id>","V","Part 2"] and section rows
    # ["Part 1 · Intro–19","<id>","V"] — harvest every plausible Drive id.
    ids = set(re.findall(r'"([A-Za-z0-9_-]{25,})"', text))
    return sorted(ids)


def existing_assets():
    r = subprocess.run([GH, "release", "view", TAG, "--repo", REPO, "--json", "assets"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return None  # release absent
    return {a["name"] for a in json.loads(r.stdout)["assets"]}


def release_id():
    r = subprocess.run([GH, "api", f"repos/{REPO}/releases/tags/{TAG}", "-q", ".id"],
                       capture_output=True, text=True, check=True)
    return r.stdout.strip()


def upload_asset(rid, path, name):
    """Upload with an EXPLICIT audio/mpeg content type. `gh release upload`
    sends application/octet-stream, and the release CDN both echoes that type
    AND serves X-Content-Type-Options: nosniff — a combination Chromium's
    media elements refuse. The uploads API takes the asset's stored type from
    this request's Content-Type header; the signed download URL then carries
    rsct=audio/mpeg and <audio> plays it."""
    return subprocess.run(
        [GH, "api", "--method", "POST",
         "-H", "Content-Type: audio/mpeg",
         f"https://uploads.github.com/repos/{REPO}/releases/{rid}/assets?name={name}",
         "--input", path],
        capture_output=True, text=True)


def main():
    limit = 0
    if "--limit" in sys.argv:
        limit = int(sys.argv[sys.argv.index("--limit") + 1])
    dry = "--dry" in sys.argv

    ids = manifest_ids()
    print(f"manifest ids: {len(ids)}")

    have = existing_assets()
    if have is None:
        if dry:
            print(f"would create release {TAG}")
            have = set()
        else:
            subprocess.run([GH, "release", "create", TAG, "--repo", REPO,
                            "--title", "Audio Letters (streaming mirror)",
                            "--notes", "Streaming mirror of the flock's audio-letter tracks. "
                                       "Assets are named <driveFileId>.mp3; regenerated by "
                                       "tools/mirror-audio-release.py. Drive blocks cross-site "
                                       "streaming (sec-fetch 403), so the app streams from here."],
                           check=True)
            have = set()
    print(f"release has: {len(have)} assets")

    todo = [i for i in ids if (i + ".mp3") not in have]
    if limit:
        todo = todo[:limit]
    print(f"to mirror: {len(todo)}{' (dry run)' if dry else ''}")
    if dry:
        for i in todo[:10]:
            print("  would mirror", i)
        return 0

    os.makedirs(STAGING, exist_ok=True)
    rid = release_id()
    ok = fail = 0
    for n, fid in enumerate(todo, 1):
        dst = os.path.join(STAGING, fid + ".mp3")
        if not (os.path.exists(dst) and os.path.getsize(dst) > 0):
            got = None
            # gdown RAISES on quota/permission walls (it doesn't just return
            # None), and bulk runs do trip Drive's rate limiting — so catch,
            # back off harder each attempt, and keep the run alive. A file
            # that stays stuck is reported and retried by the NEXT run
            # (the script is additive/idempotent).
            for attempt in (1, 2, 3):
                try:
                    got = gdown.download(id=fid, output=dst, quiet=True)
                except Exception as e:
                    print(f"  [{n}/{len(todo)}] gdown error {fid} (attempt {attempt}): {str(e).splitlines()[0][:120]}")
                    got = None
                if got:
                    break
                time.sleep(10 * attempt)
            if not got or not os.path.exists(dst) or os.path.getsize(dst) == 0:
                print(f"  [{n}/{len(todo)}] DOWNLOAD FAILED {fid}")
                fail += 1
                if os.path.exists(dst):
                    os.remove(dst)
                continue
        time.sleep(1.0)  # be gentle with Drive across a 700-file run
        r = upload_asset(rid, dst, fid + ".mp3")
        if r.returncode != 0:
            print(f"  [{n}/{len(todo)}] UPLOAD FAILED {fid}: {r.stderr.strip()[:160]}")
            fail += 1
            continue
        os.remove(dst)  # keep staging lean; the release is the mirror
        ok += 1
        if n % 10 == 0 or n == len(todo):
            print(f"  [{n}/{len(todo)}] ok={ok} fail={fail}")
    print(f"DONE ok={ok} fail={fail}")
    return 2 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
